<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace dmstr\oauth\modules\admin\models\base;

use Yii;
use \dmstr\oauth\modules\admin\models\query\ClientQuery;

/**
 * This is the base-model class for table "app_oauth_client".
 *
 * @property string $id
 * @property string $name
 * @property string $secret_hash
 * @property integer $access_token_user_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \dmstr\oauth\modules\admin\models\User $accessTokenUser
 */
abstract class Client extends \dmstr\oauth\modules\admin\models\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'app_oauth_client';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'name', 'secret_hash'], 'required'],
            [['access_token_user_id', 'created_by', 'updated_by'], 'default', 'value' => null],
            [['access_token_user_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['id'], 'string', 'max' => 80],
            [['name', 'secret_hash'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['id'], 'unique'],
            [['access_token_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \dmstr\oauth\modules\admin\models\User::class, 'targetAttribute' => ['access_token_user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('oauth', 'ID'),
            'name' => Yii::t('oauth', 'Name'),
            'secret_hash' => Yii::t('oauth', 'Secret Hash'),
            'access_token_user_id' => Yii::t('oauth', 'Access Token User ID'),
            'created_at' => Yii::t('oauth', 'Created At'),
            'updated_at' => Yii::t('oauth', 'Updated At'),
            'created_by' => Yii::t('oauth', 'Created By'),
            'updated_by' => Yii::t('oauth', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessTokenUser()
    {
        return $this->hasOne(\dmstr\oauth\modules\admin\models\User::class, ['id' => 'access_token_user_id']);
    }

    /**
     * @inheritdoc
     * @return ClientQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ClientQuery(static::class);
    }
}
