<?php

namespace dmstr\oauth;

class Module extends \yii\base\Module
{
    /**
     * Time to live for the access token generated by the token controller
     * Duration value in ISO 8601
     *
     * @link https://en.wikipedia.org/wiki/ISO_8601#Durations
     * @var string
     */
    public string $accessTokenTtl = 'PT1H';

    /**
     * Issuer of the access token
     *
     * @var string
     */
    public string $accessTokenIssuer;

    /**
     * Path to private key file. Must start with file://
     *
     * @var string
     */
    public string $tokenPrivateKey;

    /**
     * Private key passphrase
     *
     * @var string
     */
    public string $tokenEncryptionKey;

    /**
     * Identifier attribute of the user model which will be eventually added to tokens
     *
     * @var string
     */
    public string $userIdAttribute = 'id';
}
