<?php
/**
 * /app/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
 *
 * @var yii\web\View $this
 * @var dmstr\oauth\modules\admin\models\Client $model
 */
$copyParams = $model->attributes;

$this->title = Yii::t('oauth', 'Client');
$this->params['breadcrumbs'][] = ['label' => Yii::t('oauth.plural', 'Client'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('oauth', 'View');
?>
<div class="giiant-crud client-view">

    <h1>
        <?php echo Html::encode($model->name) ?>
        <small><?php echo Yii::t('oauth', 'Client') ?></small>
    </h1>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?php
echo Html::a(
    '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('oauth', 'Edit Client'),
    [ 'update', 'id' => $model->id],
    ['class' => 'btn btn-info']
)
?>

            <?php
echo Html::a(
    '<span class="glyphicon glyphicon-copy"></span> ' . Yii::t('oauth', 'Copy Client'),
    ['create', 'id' => $model->id, 'Client'=>$copyParams],
    ['class' => 'btn btn-success']
)
?>

            <?php
echo Html::a(
    '<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('oauth', 'New Client'),
    ['create'],
    ['class' => 'btn btn-success']
)
?>
        </div>

        <div class="pull-right">
            <?php echo Html::a('<span class="glyphicon glyphicon-list"></span> '
    . Yii::t('oauth', 'Full list'), ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('dmstr\oauth\modules\admin\models\Client'); ?>


    <?php
echo DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
            [
                'format' => 'html',
                'attribute' => 'access_token_user_id',
                'value' => ($model->accessTokenUser ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['/oauth/admin/user/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->accessTokenUser->label, ['/oauth/admin/user/view', 'id' => $model->accessTokenUser->id, ]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Client'=>['access_token_user_id' => $model->access_token_user_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            'created_at:datetime',
            'updated_at:datetime',
            [
                'attribute' => 'created_by',
                'value' => function ($model) {
                    $user = dmstr\oauth\modules\admin\models\User::findOne($model->created_by);
                    if ($user) {
                        return yii\helpers\Html::a($user->label, ['/oauth/admin/user/view', 'id' => $model->created_by]);
                    }
                    return null;
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'updated_by',
                'value' => function ($model) {
                    $user = dmstr\oauth\modules\admin\models\User::findOne($model->updated_by);
                    if ($user) {
                        return yii\helpers\Html::a($user->label, ['/oauth/admin/user/view', 'id' => $model->updated_by]);
                    }
                    return null;
                },
                'format' => 'raw'
            ],
        ],
    ]);
?>


    <hr/>

    <?php
echo Html::a(
    '<span class="glyphicon glyphicon-trash"></span> '
    . Yii::t('oauth', 'Delete Client'),
    ['delete', 'id' => $model->id],
    [
        'class' => 'btn btn-danger',
        'data-confirm' => '' . Yii::t('oauth', 'Are you sure to delete this item?') . '',
        'data-method' => 'post',
    ]
);
?>
    <?php $this->endBlock(); ?>



    <?php
echo Tabs::widget(
    [
        'id' => 'relation-tabs',
        'encodeLabels' => false,
        'items' => [
            [
                'label'   => '<b>' . \Yii::t('oauth', '# {primaryKey}', ['primaryKey' => Html::encode($model->id)]) . '</b>',
                'content' => $this->blocks['dmstr\oauth\modules\admin\models\Client'],
                'active'  => true,
            ],
        ]
    ]
);
?>
</div>
